id: 3DqwWi32VBhDCXEMmQuYAGG8YVmNoxVHpxfEEgL1R4XW
controller_name: avellaneda_stoikov_v2
controller_type: market_making
manual_kill_switch: null
candles_config: []
connector_name: binance_perpetual
trading_pair: WLD-USDT
total_amount_quote: 100.0
buy_spreads: []
sell_spreads: []
buy_amounts_pct: null
sell_amounts_pct: null
executor_refresh_time: 300
cooldown_time: 15
leverage: 20
position_mode: HEDGE
stop_loss: 0.03
take_profit: 0.02
time_limit: 2700
take_profit_order_type: 2
trailing_stop:
  activation_price: 0.015
  trailing_delta: 0.003
target_base_quote_ratio: 0.5
inventory_risk_aversion: 0.5
gamma: 2.0
kappa: 7.25
candles_connector: binance
candles_trading_pair: WLD-USDT
interval: 30m
max_records: 1000
natr_length: 30
